name: testenv
on:
  pull_request: :
    branches:
       - main

jobs:
 dislay:
   runs-on: ubuntu-latest
   steps:
     - name: message1
       run: echo "Good Morning"
     - name: message2
       run: cat /etc/passwd
