name: workflow2
on:
  pull_request:
    branches:
       - main

jobs:
 myjob:
   runs-on: ubuntu-latest
   steps:
     - name: print message
       run: echo "Good Morning"
     - name: another message
       run: cat /etc/passwd
