name: workflow6
on:
   workflow_dispatch
      
      
     
jobs:
   myjob:
     runs-on: ubuntu-latest
     steps:
        - name: print env variable
          run: echo 'value is ${{ vars.UNAME  }}'
        - name: print my secret value
          run: echo "password is {{ secrets.PASSWD }}"
