name: workflow6
on:
   push:
     branches: [main]
      
      
     
jobs:
   myjob:
     runs-on: ubuntu-latest
     steps:
        - name: print env variable
          run: echo 'value is ${{ vars.UNAME  }}'
        - name: print my secret value
          run: echo "password is ${{ secrets.PASSWD }}"
